In [1]:
import hw6Gauss_Quadrature as gq
import unittest
import hw6Basis_Functions as bf
import inspect
import hw6Poisson_1D as pp
import hw6Boundary_Conditions as bc
import math
import functools as ft
import numpy as np
import matplotlib.pyplot as plt


In [2]:
ien = pp.CreateIENArray(deg=2, n_elem=4)
ien



array([[0, 2, 4, 6],
       [1, 3, 5, 7],
       [2, 4, 6, 8]])

In [3]:
bcl = bc.BoundaryCondition("left", "Neu", 0, 1, 0)
bcr = bc.BoundaryCondition("right", "Dir", 1, 0, 0)

id = pp.CreateIDArray(bc_left=bcl, bc_right=bcr, deg=2, n_elem=4)
id

array([ 0,  1,  2,  3,  4,  5,  6,  7, -1])

In [5]:
xvals = pp.CreateXVals(0,1,ien)
# xvals

# LocalStiffness(e, xvals, bc_left, bc_right, deg)
ke = pp.LocalStiffness(e=0, xvals=xvals, bc_left=bcl, bc_right=bcr, deg=2)
ke

array([[ 5.33333333, -2.66666667, -2.66666667],
       [-2.66666667,  5.33333333, -2.66666667],
       [-2.66666667, -2.66666667,  5.33333333]])

In [ ]:
fe = pp.LocalForce(e=0,xvals=xvals,n_elem_funcs=3,bc_left=bcl, bc_right=bcr,)