In [25]:
import p3Basis_Functions_2D as bf
import p3Gauss_Quadrature_2D as gq
import p3Boundary_Conditions as bc
import p3Diffusion_2D as d2
import p3Surface_Mesh as sm
import numpy as np
import inspect

In [26]:
prob3 = d2.run_problem(3)
m3 = prob3.mesh
bounds3 = prob3.boundaries
vs = d2.get_all_vertices(m3)

![title](_mesh-image-ks.png)

In [43]:
# global x,y,z coordinate points for a given face
m3.get_face_points(3)

array([[0.        , 4.99524267, 0.        ],
       [0.        , 0.        , 0.        ],
       [5.00513363, 0.        , 0.        ],
       [4.9994216 , 5.00014795, 0.        ]])

In [27]:
m3.boundary_vertices()



[0, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]

In [42]:
for v in vs:
    if m3.vertex_is_boundary(v):
        print(v)
    else:
        continue


# m3.vertex_is_boundary(vs[0])

0
3
4
5
6
7
8
10
11
12
13
14


In [28]:
m3.boundary_edges()

[(11, 12),
 (5, 4),
 (8, 7),
 (0, 3),
 (6, 5),
 (4, 11),
 (10, 0),
 (13, 14),
 (7, 6),
 (3, 8),
 (14, 10),
 (12, 13)]

In [29]:
m3.faces

array([[ 0,  1,  2,  3],
       [ 4,  5,  2,  1],
       [ 5,  6,  7,  2],
       [ 7,  8,  3,  2],
       [10,  9,  1,  0],
       [ 1,  9, 11,  4],
       [ 9, 13, 12, 11],
       [ 9, 10, 14, 13]])

In [30]:
minn = min(m3.faces[0])
minn + 1

1

In [31]:
max(m3.faces[0])
def get_all_vertices(mesh):
    fcs = mesh.faces
    loop = len(fcs)
    mins = []
    maxes = []
    for i in range(0, loop):
        f_vs = fcs[i]
        f_min = min(f_vs)
        f_max = max(f_vs)
        mins.append(f_min)
        maxes.append(f_max)
    min_ = min(mins)
    max_ = max(maxes) + 1
    vs = np.arange(min_, max_, 1, int)
    return vs

allvs = get_all_vertices(m3)
allvs[-1]
len(allvs)
allvs


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.arange(0, 14, 1, int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [33]:
bc.get_NTE(bounds3)

{'00_NTE': 1,
 '0_BCType.Neumann': {6: [(7, 6)], 7: [(8, 7), (7, 6)], 8: [(8, 7)]},
 '1_BCType.Dirichlet': {0: [(0, 3), (10, 0)],
                        3: [(0, 3), (3, 8)],
                        8: [(3, 8)],
                        10: [(10, 0), (14, 10)],
                        14: [(14, 10)]},
 '2_BCType.Neumann': {12: [(12, 13)], 13: [(13, 14), (12, 13)], 14: [(13, 14)]},
 '3_BCType.Neumann': {4: [(5, 4), (4, 11)],
                      5: [(5, 4), (6, 5)],
                      6: [(6, 5)],
                      11: [(11, 12), (4, 11)],
                      12: [(11, 12)]}}


In [34]:
bc.get_ESS(bounds3)

{'00_ESS': 1,
 '0_BCType.Neumann': [(8, 7), (7, 6)],
 '1_BCType.Dirichlet': [(0, 3), (10, 0), (3, 8), (14, 10)],
 '2_BCType.Neumann': [(13, 14), (12, 13)],
 '3_BCType.Neumann': [(11, 12), (5, 4), (6, 5), (4, 11)]}


In [35]:
ddofs = bc.get_dirdofs(bounds3)
ddofsset = ddofs.dirichlet_dofs_set

In [36]:
ddofsset

{0, 3, 8, 10, 14}