In [7]:
import p3Basis_Functions_2D as bf
import p3Gauss_Quadrature_2D as gq
import p3Boundary_Conditions as bc
import p3Diffusion_2D as d2
import p3Surface_Mesh as sm
import numpy as np
import inspect
import pprint as pp
# 22.6 seconds for this cell to run???
# 1.3s this time

In [8]:
prob3 = d2.run_problem(3)
m3 = prob3.mesh
bounds3 = prob3.boundaries
ddofs = bc.get_dirdofs(bounds3).dd
ien = d2.CreateIENArray(m3)
id = d2.CreateIDArray(m3, ddofs)
vs = d2.get_all_vertices(m3)

In [45]:
ddofs

[0, 3, 8, 10, 14]

In [11]:
ien

array([[ 0,  4,  5,  7, 10,  1,  9,  9],
       [ 1,  5,  6,  8,  9,  9, 13, 10],
       [ 2,  2,  7,  3,  1, 11, 12, 14],
       [ 3,  1,  2,  2,  0,  4, 11, 13]])

In [12]:
id

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [-1,  0,  1, -1,  2,  3,  4,  5, -1,  6, -1,  7,  8,  9, -1]])

In [54]:
a = 0 # 0-3
e = 0 # 0-14
ien[a,e]

def looper(mesh_, ien_, id_):
    i_arr = [0,1,2,3]
    v_arr = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]
    f_arr = mesh_.faces
    n_elems = len(f_arr)
    n_unknowns = int(max(id_[1])) + 1
    print(f"n_unknowns = {n_unknowns}")
    F = np.zeros((n_unknowns,1)) # len 10
    print(F)
    K = np.zeros((n_unknowns,n_unknowns))
    ienlist = []
    idlist = []
    Flist = []
    for e in range(0, len(f_arr)):
        print(f"ELEMENT #{e}") # 0-7
        fe = np.array((e+10, e+100))
        for i in range(0, len(i_arr)):
            P = ien_[i,e] # the vertex index
            
            A = id_[1][P]

            # print(f"P is {P}")
            # print(f"A is {A}")
            if A == -1:
                continue
            print(f"A is {A}")
            ienlist.append(P)
            idlist.append(A)
            # F[A] += fe[a]
    print(ienlist)
    print(f"len ienlist = {len(ienlist)}")
    print(idlist)
    print(f"len idlist = {len(idlist)}")
    # return ienlist, idlist


In [55]:
looper(m3, ien, id)

n_unknowns = 10
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ELEMENT #0
A is 0
A is 1
ELEMENT #1
A is 2
A is 3
A is 1
A is 0
ELEMENT #2
A is 3
A is 4
A is 5
A is 1
ELEMENT #3
A is 5
A is 1
ELEMENT #4
A is 6
A is 0
ELEMENT #5
A is 0
A is 6
A is 7
A is 2
ELEMENT #6
A is 6
A is 9
A is 8
A is 7
ELEMENT #7
A is 6
A is 9
[1, 2, 4, 5, 2, 1, 5, 6, 7, 2, 7, 2, 9, 1, 1, 9, 11, 4, 9, 13, 12, 11, 9, 13]
len ienlist = 24
[0, 1, 2, 3, 1, 0, 3, 4, 5, 1, 5, 1, 6, 0, 0, 6, 7, 2, 6, 9, 8, 7, 6, 9]
len idlist = 24
