In [2]:
import basis as bs
import mesh as mm
import integrate as ig
import assembly as asm
import numpy.polynomial.legendre as lg
import numpy as np

arr1 is 
[[0.125]
 [0.25 ]
 [0.25 ]
 [0.25 ]
 [0.125]]


In [3]:
def fast_fe(e, mesh, f):
    e_dom = mm.generate_elements(mesh).get_element_domain(e)
    print(f"e dom is {e_dom}")
    e_x0 = e_dom[0]
    e_x1 = e_dom[1]
    f_x0 = f(e_x0)
    f_x1 = f(e_x1)
    print(f"f() of the dom pts: {f_x0} and {f_x1}")
    f_21 = (2*f_x0 + f_x1)
    print(f"2f1 + f2 is {f_21}")
    f_12 = (f_x0 + 2 * f_x1)
    print(f"f1 + 2f2 is {f_12}")
    he = e_x1 - e_x0
    print(f"he is {he}, so he/6 is {he/6}")
    fe_0 = he/6 * f_21
    print(f"he6*(2f1 + f2) is {fe_0}")
    fe_1 = he/6 * f_12
    print(f"he6*(f1 + 2f2) is {fe_1}")
    fe = np.array(([fe_0], [fe_1]))
    return fe

In [4]:
m1 = mm.generate_mesh(0, 1, 2)
m1e = mm.generate_elements(m1)
m1e.get_element_domain(1) # array([0., 1.])


array([0.5, 1. ])

In [5]:
f1 = lambda x: x
m10fe = fast_fe(0,m1,f1)
m10fe

# so for 0,1 and 2 elements with f=1, fe entries are 0.25
# and for same with f = x, fe entries are array([[0.04166667],[0.08333333]])

# now question is whether we can get the same results from the full calculation

e dom is [0.  0.5]
f() of the dom pts: 0.0 and 0.5
2f1 + f2 is 0.5
f1 + 2f2 is 1.0
he is 0.5, so he/6 is 0.08333333333333333
he6*(2f1 + f2) is 0.041666666666666664
he6*(f1 + 2f2) is 0.08333333333333333


array([[0.04166667],
       [0.08333333]])

In [6]:
# def gen_fe_2(mesh,e):
#     mx_ = np.zeros((2,1))
#     els = mesh.generate_elements
#     e_dom = mm.get_element_domain(e)
#     e_x0 = e_dom[0]
#     e_x1 = e_dom[1]
#     for a in range(0,2):
#         N_a_term = bs.eval_basis(xmin=e_x0, xmax=e_x1, bf_idx=a, x_in=0)
#         def quad_fn(xi=0, a=0, b=0):
#             return lambda xi: 
#         integrand = lambda x: N_a(x) * forcing_function(x)
#         integrand = lambda x: bs.eval_basis(xmin=e_x0, xmax=e_x1, bf_idx=a, x_in=x)
#         fe[a] = integrate_by_quadrature(function=integrand, x_lower=xmin, x_upper=xmax, n_quad=1)

In [7]:

def gen_fe2(mesh, e, f):
    print(f"\n gen_fe for element idx={e}")
    # temp fast_fe
    mesh = mm.generate_mesh(0,1,4)
    e_dom = mm.generate_elements(mesh).get_element_domain(e)
    e_x0 = e_dom[0]
    e_x1 = e_dom[1]
    # f_x0 = f(e_x0)
    # f_x1 = f(e_x1)
    # f_x = lambda x: f(x)
    # Na_x = lambda a, x: bs.eval_basis(bf_idx=a, xmin=e_x0, xmax = e_x1, x_in=x)
    # prod_ = lambda a, x: Na_x(x) * f_x(x)
    for a in range(0,2):
        fe = np.zeros((2,1))
        Na_xi = lambda xi: bs.eval_basis(bf_idx=a, xmin=e_x0, xmax = e_x1, x_in=xi)
        f_xi = lambda xi: f(xi)
        prod = lambda xi: Na_xi(xi) * f_xi(xi)
        integ = ig.integrate_by_quadrature(function=prod, x_lower=e_x0, x_upper=e_x1, n_quad=1)
        print(f"integral of Na*f = {integ}")        
        fe[a] += integ
    return fe

ffnn = lambda x: 1
m4 = mm.generate_mesh(0, 1, 4)
gen_fe2(m4, 0, ffnn)


 gen_fe for element idx=0
integral of Na*f = 2.0
integral of Na*f = 0.0


array([[0.],
       [0.]])