In [1]:
import hw7Gauss_Quadrature as gq
import unittest
import hw7Basis_Functions as bf
import inspect
import hw7Poisson_1D as p1
import hw7Boundary_Conditions as bc
import hw7Problems_Revised as pb
import math
import functools as ft
import numpy as np
import matplotlib.pyplot as plt
import hw7Error_Values as ev
from matplotlib.ticker import ScalarFormatter
import matplotlib.ticker as ticker


## Problem data

In [2]:
f = lambda x: 20 * math.sin(15 * x)
bcl = bc.BoundaryCondition("left", "Neu", 0, 1, -1)
bcr = bc.BoundaryCondition("right", "Dir", 1, 0, 2)
u_exact = lambda x: 2 + (1 - x) - (4/45)*math.sin(15) + (4/3) + (4/45)*math.sin(15*x) - (4*x/3)
u_exact_derv = lambda x: (4/3)*math.cos(15 * x) - (7/3)


## Plots for p = 1, 2

In [3]:
# err_deg_1 = p1.PlotConvergenceComparison(deg=1, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv)

# err_deg_1.plot_l2_h1_errs()

In [4]:
# err_deg_2 = p1.PlotConvergenceComparison(deg=2, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv)

# err_deg_2.plot_l2_h1_errs()

## Plots for p = 3, 4, 5 (problem)

For degrees 3 - 5 my FEM_Poisson1D code is generating an error (`LinAlgError: Singular matrix`) at the `np.linalg.solve` line. 

I haven't been able to figure out why yet -- still working on that. 


### testing p=2 output of parts and whole

In [5]:
xvals = p1.CreateXVals(0,1,2)

p1.LocalStiffness(0, xvals, bcl, bcr, 2)
# array([[ 2.66666667, -1.33333333, -1.33333333],
#        [-1.33333333,  2.66666667, -1.33333333],
#        [-1.33333333, -1.33333333,  2.66666667]])

array([[ 2.66666667, -1.33333333, -1.33333333],
       [-1.33333333,  2.66666667, -1.33333333],
       [-1.33333333, -1.33333333,  2.66666667]])

In [6]:
# deg=3, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv

p1.FEM_Poisson(bcl, bcr, f, xvals, 2)
# KE0 AS CALCD BY FEM_POISSON
# [[ 2.66666667 -1.33333333 -1.33333333]
#  [-1.33333333  2.66666667 -1.33333333]
#  [-1.33333333 -1.33333333  2.66666667]]
# KE1 AS CALCD BY FEM_POISSON
# [[ 2.66666667 -1.33333333 -1.33333333]
#  [-1.33333333  2.66666667 -1.33333333]
#  [-1.33333333 -1.33333333  2.66666667]]

# K GLOBAL AS CALCD BY FEM_POISSON
# [[ 2.66666667 -1.33333333 -1.33333333  0.        ]
#  [-1.33333333  2.66666667 -1.33333333  0.        ]
#  [-1.33333333 -1.33333333  5.33333333 -1.33333333]
#  [ 0.          0.         -1.33333333  2.66666667]]

STARTING FEM_POISSON
calc'd n_quad for p=2 is 5
ke for elem 0 is 
[[ 2.66666667 -1.33333333 -1.33333333]
 [-1.33333333  2.66666667 -1.33333333]
 [-1.33333333 -1.33333333  2.66666667]]
fe for elem 0 is 
[[ 5.27937711]
 [ 1.06672722]
 [-0.89592266]]
ke for elem 1 is 
[[ 2.66666667 -1.33333333 -1.33333333]
 [-1.33333333  2.66666667 -1.33333333]
 [-1.33333333 -1.33333333  2.66666667]]
fe for elem 1 is 
[[ 3.8709222 ]
 [ 4.47292455]
 [-2.9250731 ]]
final K is 
[[ 2.66666667 -1.33333333 -1.33333333  0.        ]
 [-1.33333333  2.66666667 -1.33333333  0.        ]
 [-1.33333333 -1.33333333  5.33333333 -1.33333333]
 [ 0.          0.         -1.33333333  2.66666667]]
final F is 
[[5.27937711]
 [1.06672722]
 [2.97499954]
 [4.47292455]]


array([[8.68515343],
       [7.63199096],
       [5.77878307],
       [4.56673824]])

In [7]:
# err_deg_3 = p1.PlotConvergenceComparison(deg=3, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv)

# err_deg_3.plot_l2_h1_errs()

In [8]:
# err_deg_4 = p1.PlotConvergenceComparison(deg=4, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv)

# err_deg_4.plot_l2_h1_errs()

In [9]:
# err_deg_5 = p1.PlotConvergenceComparison(deg=5, bcl=bcl, bcr=bcr, f=f, u_exact=u_exact, u_exact_derv=u_exact_derv)

# err_deg_5.plot_l2_h1_errs()