In [1]:
import hw7Gauss_Quadrature as gq
import unittest
import hw7Basis_Functions as bf
import inspect
import hw7Poisson_1D as p1
import hw7Boundary_Conditions as bc
import hw7Problems_Revised as pb
import math
import functools as ft
import numpy as np
import matplotlib.pyplot as plt
import hw7Error_Values as ev
from matplotlib.ticker import ScalarFormatter
import matplotlib.ticker as ticker


## Problem data

In [2]:
f = lambda x: 20 * math.sin(15 * x)
bcl = bc.BoundaryCondition("left", "Neu", 0, 1, -1)
bcr = bc.BoundaryCondition("right", "Dir", 1, 0, 2)
u_exact = lambda x: 2 + (1 - x) - (4/45)*math.sin(15) + (4/3) + (4/45)*math.sin(15*x) - (4*x/3)
u_exact_derv = lambda x: (4/3)*math.cos(15 * x) - (7/3)
xvals = p1.CreateXVals(0,1,4)


In [10]:
fp1 = p1.FEM_Poisson(bcl,bcr,f,xvals,3)
ien = fp1[0]
id = fp1[1]
# np.linalg.det(K)
print(f"ien\n{ien}\nid\n{id}")

ien
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
id
[ 0  1  2  3  4  5  6  7  8  9 10 11 -1]


In [6]:
kelist = fp1[4]
kelist

[array([[ 7., -3., -3., -1.],
        [-3.,  3.,  3., -3.],
        [-3.,  3.,  3., -3.],
        [-1., -3., -3.,  7.]]),
 array([[ 7., -3., -3., -1.],
        [-3.,  3.,  3., -3.],
        [-3.,  3.,  3., -3.],
        [-1., -3., -3.,  7.]]),
 array([[ 7., -3., -3., -1.],
        [-3.,  3.,  3., -3.],
        [-3.,  3.,  3., -3.],
        [-1., -3., -3.,  7.]]),
 array([[ 7., -3., -3., -1.],
        [-3.,  3.,  3., -3.],
        [-3.,  3.,  3., -3.],
        [-1., -3., -3.,  7.]])]

In [8]:
K = fp1[2]
K

array([[ 7., -3., -3., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -3., -3., 14., -3., -3., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., -3., -3., 14., -3., -3., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1., -3., -3., 14., -3., -3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3.]])

In [11]:
arr = np.array([[ 7., -3., -3., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -3., -3., 14., -3., -3., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., -3., -3., 14., -3., -3., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3., -3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1., -3., -3., 14., -3., -3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3.,  3.,  3.]])

In [13]:
np.linalg.det(arr)

0.0